---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Energy
--- 
components: 
  schemas: 
    ThreePhaseAcMeasurement: 
      $ref: "https://smart-data-models.github.io/dataModel.Energy/ThreePhaseAcMeasurement/model.yaml#/ThreePhaseAcMeasurement"
info: 
  description: |
    A ThreePhaseAcMeasurement entity represents a measurement from an electrical system that uses three-phase alternating current. It has attributes for various electrical measurements such as power, frequency, current and voltage. For some attributes such as current and voltage the value is a structured value with properties for the three different phases: L1, L2 and L3. For some measurements such as the different power types (active, reactive and apparent power) there is an attribute for the total from all phases e.g. totalActivePower and an attribute for values from each phase as a structured value e.g. activePower. There are also attributes for different energy types: active (delivered net energy), reactive and apparent. They are cumulative values and the start time for their measurement can be saved to the dateEnergyMeteringStarted attribute.

  title: ThreePhaseAcMeasurement
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - ThreePhaseAcMeasurement
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Energy/ThreePhaseAcMeasurement/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Energy/ThreePhaseAcMeasurement/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
