--- 
components: 
  schemas: 
    ThreePhaseAcMeasurement: 
      $ref: "https://smart-data-models.github.io/dataModel.Energy/28f3f994702dc75318cfae247959c24d7d0d3968/ThreePhaseAcMeasurement/model.yaml#/ThreePhaseAcMeasurement"
info: 
  description: >-
    An electrical  measurement from a system that uses three phase alternating
  title: ThreePhaseAcMeasurement
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - ThreePhaseAcMeasurement
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.UrbanMobility/ThreePhaseAcMeasurement/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.UrbanMobility/ThreePhaseAcMeasurement/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
